
import sys
import os
import json
import pytest

# Add backend to path
sys.path.append(os.path.join(os.path.dirname(__file__), ".."))

from services.oracle.runner import run_cli_oracle

def test_runner_output_files_validation():
    """
    Test that the runner correctly validates output files generated by the script.
    """
    # 1. Test case where the script generates the expected file with correct content
    code_success = """
with open("output.txt", "w") as f:
    f.write("Hello World")
print("Done")
"""
    test_case_success = {
        "name": "success_case",
        "input": [],  # No args
        "expected": {
            "stdout": "Done",
            "files": {
                "output.txt": "Hello World"
            }
        }
    }
    
    # Correct signature: code, tests, timeout, stdout_max, stderr_max, sandbox_mode, limits
    result_dict = run_cli_oracle(
        code_success, 
        [test_case_success], 
        timeout_sec_per_test=5.0,
        stdout_max_bytes=1000,
        stderr_max_bytes=1000,
        sandbox_mode="local",
        resource_limits={}
    )
    
    parsed = result_dict["parsed"]
    print("\n--- Success Case ---")
    print(f"Passed: {parsed['passed']}")
    print(f"Failures: {parsed['failures']}")
    
    assert parsed['passed'] == 1
    assert parsed['failed'] == 0
    assert len(parsed['failures']) == 0

    # 2. Test case where the script generates the file but content mismatches
    code_mismatch = """
with open("output.txt", "w") as f:
    f.write("Wrong Content")
print("Done")
"""
    test_case_mismatch = {
        "name": "mismatch_case",
        "input": [],
        "expected": {
            "stdout": "Done",
            "files": {
                "output.txt": "Hello World"
            }
        }
    }
    
    result_dict_mismatch = run_cli_oracle(
        code_mismatch, 
        [test_case_mismatch], 
        timeout_sec_per_test=5.0,
        stdout_max_bytes=1000,
        stderr_max_bytes=1000,
        sandbox_mode="local",
        resource_limits={}
    )
    parsed_mismatch = result_dict_mismatch["parsed"]
    
    print("\n--- Mismatch Case ---")
    print(f"Passed: {parsed_mismatch['passed']}")
    print(f"Failures: {parsed_mismatch['failures']}")
    
    assert parsed_mismatch['passed'] == 0
    assert parsed_mismatch['failed'] == 1
    assert "content mismatch" in str(parsed_mismatch['failures'][0]["got"]) or "content mismatch" in str(parsed_mismatch['failures'][0].get("error", ""))

    # 3. Test case where the script fails to generate the file
    code_missing = """
print("Done")
"""
    test_case_missing = {
        "name": "missing_case",
        "input": [],
        "expected": {
            "stdout": "Done",
            "files": {
                "output.txt": "Hello World"
            }
        }
    }
    
    result_dict_missing = run_cli_oracle(
        code_missing, 
        [test_case_missing], 
        timeout_sec_per_test=5.0,
        stdout_max_bytes=1000,
        stderr_max_bytes=1000,
        sandbox_mode="local",
        resource_limits={}
    )
    parsed_missing = result_dict_missing["parsed"]

    print("\n--- Missing File Case ---")
    print(f"Passed: {parsed_missing['passed']}")
    print(f"Failures: {parsed_missing['failures']}")
    
    assert parsed_missing['passed'] == 0
    assert parsed_missing['failed'] == 1
    assert "missing" in str(parsed_missing['failures'][0]["got"]) or "missing" in str(parsed_missing['failures'][0].get("error", ""))

if __name__ == "__main__":
    try:
        test_runner_output_files_validation()
        print("\nAll output file validation tests passed!")
    except AssertionError as e:
        print(f"\nTest failed: {e}")
        sys.exit(1)
    except Exception as e:
        print(f"\nAn error occurred: {e}")
        import traceback
        traceback.print_exc()
        sys.exit(1)
