
import requests
import json
import sqlite3
import time

BASE_URL = "http://127.0.0.1:8001/api/oracle"
DB_PATH = "backend.db"

def get_db_connection():
    return sqlite3.connect(DB_PATH)

def print_section(title):
    print(f"\n{title}")

def run_task(desc, deliverable):
    # Create Task
    resp = requests.post(f"{BASE_URL}/task", json={"project_id": "verify"})
    task_id = resp.json()["task_id"]
    
    # Create Spec
    payload = {
        "task_description": desc,
        "deliverable_type": deliverable,
        "debug_invalid_mock": False
    }
    resp = requests.post(f"{BASE_URL}/task/{task_id}/version/spec", json=payload)
    return resp.json()

def get_debug_info():
    resp = requests.get(f"{BASE_URL}/debug/last_spec_call")
    return resp.json()

def main():
    # (1) Code snippet locations
    print_section("(1) Code snippet locations:")
    print("    - where request_id is extracted: backend/services/llm_service.py (in chat method return dict)")
    print("    - where latency_ms t0/t1 is measured: backend/services/llm_service.py (start_time vs time.time())")

    # (2) PRAGMA table_info
    print_section("(2) PRAGMA table_info(...) output (or ORM schema proof)")
    conn = get_db_connection()
    cursor = conn.cursor()
    cursor.execute("PRAGMA table_info(oracle_task_versions)")
    cols = cursor.fetchall()
    print(cols)
    conn.close()

    # (3) Run A: Analyze response JSON + /oracle/debug/last_spec_call JSON
    print_section("(3) Run A: Analyze response JSON + /oracle/debug/last_spec_call JSON")
    desc_a = "CLI tool that reads a list of numbers from stdin (one per line) and prints the sum to stdout."
    res_a = run_task(desc_a, "cli")
    print(json.dumps(res_a, indent=2))
    debug_a = get_debug_info()
    print(json.dumps(debug_a, indent=2))

    # (4) Run B: Analyze response JSON + /oracle/debug/last_spec_call JSON
    print_section("(4) Run B: Analyze response JSON + /oracle/debug/last_spec_call JSON")
    desc_b = "Process the user list to improve performance."
    res_b = run_task(desc_b, "function")
    print(json.dumps(res_b, indent=2))
    debug_b = get_debug_info()
    print(json.dumps(debug_b, indent=2))

    # (5) JSON list of 5 real request_id records
    print_section("(5) JSON list of 5 real request_id records (from DB or debug output)")
    conn = get_db_connection()
    conn.row_factory = sqlite3.Row
    cursor = conn.cursor()
    cursor.execute("SELECT version_id, spec_llm_request_id, llm_model_used, llm_latency_ms, attempts FROM oracle_task_versions WHERE spec_llm_request_id IS NOT NULL ORDER BY created_at DESC LIMIT 5")
    rows = [dict(r) for r in cursor.fetchall()]
    print(json.dumps(rows, indent=2))
    conn.close()

    # (6) 10+ lines backend logs
    print_section("(6) 10+ lines backend logs showing provider/model/request_id/latency/status")
    try:
        with open("benchmark_logs.txt", "r") as f:
            print(f.read())
    except:
        print("benchmark_logs.txt not found (Run rerun_selected.py first)")

    # (7) 3 quality-check Analyze outputs + one underspecified mapping note
    print_section("(7) 3 quality-check Analyze outputs (ops_sequence, cli_stdio, function_single) + one underspecified mapping note")
    
    # Fetch representative outputs from DB (populated by rerun_selected.py)
    # OPS_001, CLI_001, DATA_001, AMB_001
    conn = get_db_connection()
    conn.row_factory = sqlite3.Row
    cursor = conn.cursor()
    
    # We need to map test_id to task_id using selected_benchmark_map.json
    try:
        with open("selected_benchmark_map.json", "r") as f:
            mapping = json.load(f)
    except:
        mapping = []

    target_ids = ["OPS_001", "CLI_001", "DATA_001"]
    for tid in target_ids:
        real_id = next((m["real_task_id"] for m in mapping if m["test_id"] == tid), None)
        if real_id:
            cursor.execute("SELECT spec_json FROM oracle_task_versions WHERE task_id = ? ORDER BY created_at DESC LIMIT 1", (real_id,))
            row = cursor.fetchone()
            if row:
                spec = json.loads(row["spec_json"]) if isinstance(row["spec_json"], str) else row["spec_json"]
                print(json.dumps(spec, indent=2))
    
    # Underspecified note
    tid = "AMB_001"
    real_id = next((m["real_task_id"] for m in mapping if m["test_id"] == tid), None)
    if real_id:
        cursor.execute("SELECT missing_fields_json, ambiguities_json FROM oracle_task_versions WHERE task_id = ? ORDER BY created_at DESC LIMIT 1", (real_id,))
        row = cursor.fetchone()
        if row:
            print("\nUnderspecified Task (AMB_001) Mapping:")
            print(f"Missing Fields: {row['missing_fields_json']}")
            print(f"Ambiguities: {row['ambiguities_json']}")
            print("Explanation: The 'ambiguities' array contains questions generated by the LLM to resolve the missing information or vague requirements found in the task description.")

    conn.close()

if __name__ == "__main__":
    main()
